### ISSUE TITLE
assert spec.submodule_search_locations is not None

### ISSUE THREAD

**Issue by beliaev-maksim** [asottile/reorder_python_imports#216]
today pipelines start to fail with following error.
see PR https://github.com/ansys/aedt-testing/pull/125 where we see this

```
 Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/bin/reorder-python-imports", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 907, in main
    retv |= _fix_file(filename, args)
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 475, in _fix_file
    new_contents = fix_file_contents(
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 456, in fix_file_contents
    partitioned = step(partitioned)
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 366, in apply_import_sorting
    sorted_blocks = sort(import_obj_to_partition.keys(), **sort_kwargs)
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 96, in sort
    imports_partitioned[classify_func(import_obj)].append(import_obj)
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 73, in classify_func
    return classify_import(obj.import_statement.module, **kwargs)
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 138, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/home/runner/.cache/pre-commit/repobufxvwst/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError
```

**Comment by asottile** [comment]
dupe #210 -- please search first

**Comment by beliaev-maksim** [comment]
@asottile 
but then you fixed it, then it reappeared again. Something got wrong with the fix?

**Comment by asottile** [comment]
no, you're still running old setuptools
