### ISSUE TITLE
Reordering fails with deprecated imports like `distutils.version`

### ISSUE THREAD

**Issue by int3l** [asottile/reorder_python_imports#220]
Reordering fails with some deprecated package imports like this simple one:

t.py:

```python
from distutils.version import LooseVersion

LooseVersion('1.2.3')
```

output:

```bash
(venv) [test@host pytesseract]$ pre-commit run
Reorder python imports...................................................Failed
- hook id: reorder-python-imports
- exit code: 1

Traceback (most recent call last):
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/bin/reorder-python-imports", line 8, in <module>
    sys.exit(main())
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 912, in main
    retv |= _fix_file(filename, args)
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 473, in _fix_file
    new_contents = fix_file_contents(
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 454, in fix_file_contents
    partitioned = step(partitioned)
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 364, in apply_import_sorting
    sorted_blocks = sort(import_obj_to_partition.keys(), **sort_kwargs)
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 98, in sort
    imports_partitioned[classify_func(import_obj)].append(import_obj)
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 72, in classify_func
    tp = classify_import(obj.import_statement.module, **kwargs)
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 135, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/home/test/.cache/pre-commit/repo76shnjij/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError
```

versions:

```text
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
pre-commit 2.17.0
```

pre-commit config:

```yaml
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
```

**Comment by asottile** [comment]
dupe #210

**Comment by beliaev-maksim** [comment]
@int3l 
did you manage to fix the pipe? can you share your yaml?

I tried following and still see the issue:
```yml
name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Upgrade setuptools
      run: |
        python -m pip install -U setuptools
    - uses: pre-commit/action@v2.0.3
```

**Comment by int3l** [comment]
@beliaev-maksim Either adjust the setuptools (via pyproject.toml for your project) or upgrade it manually for your environment.
In my case, I actually axed the deprecated `distutils.version` import from one of the projects that I maintain.
`packaging.version` seems to be the recommended option now and it solved the problem for me.

Also, there are a bunch of comments here: https://github.com/asottile/reorder_python_imports/issues/210
