### ISSUE TITLE
KeyError: <class '_ast.Expr'>

### ISSUE THREAD

**Issue by nicoddemus** [asottile/reorder_python_imports#57]
Hi @asottile,

I'm getting this error while trying to pytest commit locally:

```
(.env36) λ git commit -a
[INFO] Initializing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Installing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Failed
hookid: black

Files were modified by this hook.

blacken-docs.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Failed
hookid: end-of-file-fixer

Files were modified by this hook. Additional output:

Fixing changelog/4262.bugfix.rst

Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Flake8...................................................................Passed
Reorder python imports...................................................Failed
hookid: reorder-python-imports

Traceback (most recent call last):
  File "C:\Users\bruno\AppData\Local\Programs\Python\Python36-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\bruno\AppData\Local\Programs\Python\Python36-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\Scripts\reorder-python-imports.exe\__main__.py", line 9, in <module>
  File "c:\users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\lib\site-packages\reorder_python_imports.py", line 669, in main
    application_directories=args.application_directories.split(':'),
  File "c:\users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\lib\site-packages\reorder_python_imports.py", line 405, in fix_file_contents
    partitioned = step(partitioned)
  File "c:\users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\lib\site-packages\reorder_python_imports.py", line 162, in separate_comma_imports
    return list(_inner())
  File "c:\users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\lib\site-packages\reorder_python_imports.py", line 151, in _inner
    import_obj = import_obj_from_str(partition.src)
  File "c:\users\bruno\.cache\pre-commit\repo0gna_967\py_env-python3.6\lib\site-packages\aspy\refactor_imports\import_obj.py", line 189, in import_obj_from_str
    return ast_type_to_import_type[type(ast_obj)](ast_obj)
KeyError: <class '_ast.Expr'>

pyupgrade................................................................Passed
rst ``code`` is two backticks............................................Passed
rst......................................................................Passed
changelog filenames..................................(no files to check)Skipped
```

A few comments:

1. This environment was created some time ago, and as can be seen from the output, the venv for `reorder-python-imports` was just created.

1. The branch I'm working on is based on e6e40db9c7c5f585185df699513ea745a4429336.

Any hints?

**Comment by asottile** [comment]
Interesting!

Can you paste the diff on top of e6e40?

**Comment by asottile** [comment]
you can also temporarily skip the hook with `SKIP=reorder-python-imports git commit ...`

**Comment by nicoddemus** [comment]
Here's the diff: https://github.com/pytest-dev/pytest/pull/4267/commits/5384436846dc8227f6b13a9b8e617fd1794f070b


> you can also temporarily skip the hook with SKIP=reorder-python-imports git commit ...

Oh thanks, did not know that (I've skipped all hooks with `git commit -n`, but your solution is better)

**Comment by asottile** [comment]
Very peculiar!  I wasn't able to reproduce with that patch on my machine :sob: -- does it reproduce for you if you check out the original commit, apply the patch, and attempt to commit again?

**Comment by asottile** [comment]
ah! I've figured it out:

```console
$ unix2dos testing/test_pathlib.py 
unix2dos: converting file testing/test_pathlib.py to DOS format...
$ file !$
file testing/test_pathlib.py
testing/test_pathlib.py: Python script, ASCII text executable, with CRLF line terminators
$ pre-commit  run reorder-python-imports --files !$
pre-commit  run reorder-python-imports --files testing/test_pathlib.py
Reorder python imports...................................................Failed
hookid: reorder-python-imports

Traceback (most recent call last):
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/bin/reorder-python-imports", line 11, in <module>
    sys.exit(main())
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/lib/python3.6/site-packages/reorder_python_imports.py", line 669, in main
    application_directories=args.application_directories.split(':'),
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/lib/python3.6/site-packages/reorder_python_imports.py", line 405, in fix_file_contents
    partitioned = step(partitioned)
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/lib/python3.6/site-packages/reorder_python_imports.py", line 162, in separate_comma_imports
    return list(_inner())
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/lib/python3.6/site-packages/reorder_python_imports.py", line 151, in _inner
    import_obj = import_obj_from_str(partition.src)
  File "/home/asottile/.cache/pre-commit/repoyz4c9qj3/py_env-python3/lib/python3.6/site-packages/aspy/refactor_imports/import_obj.py", line 189, in import_obj_from_str
    return ast_type_to_import_type[type(ast_obj)](ast_obj)
KeyError: <class '_ast.Expr'>
```

I think I know what's wrong too, there's some line/offset partitioning that probably assumes unix line endings

Now to fix it!

**Comment by nicoddemus** [comment]
Ahh cool. 😎

**Comment by asottile** [comment]
#58 for that
